name: smartstruct_example
description: example
version: 1.0.1
# homepage: https://www.example.com
environment:
  sdk: ">=2.12.0 <3.0.0"

publish_to: none
dependencies:
  injectable: ^1.4.1
  smartstruct: ^1.1.4
dev_dependencies:
  build_runner: ^2.0.4
  # smartstruct_generator: ^1.1.2
  smartstruct_generator: ^1.1.4
   
