name: smartstruct_generator
description: smartstruct - A dart bean mapper annotation processor - the easy nullsafe way!
version: 1.2.0
homepage: https://github.com/smotastic/smartstruct
environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.17.7
  source_gen_test: ^1.0.0
dependencies:
  analyzer: ^1.7.1
  build: ^2.0.2
  source_gen: ^1.0.1
  code_builder: ^4.0.0
  # after release please replace with smartstruct: 1.1.4 
  smartstruct:
    path: ../smartstruct
  path: ^1.8.0
 