name: smartstruct
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.12.0 <3.0.0"

# dependencies:
#   path: ^1.8.0
dev_dependencies:
  pedantic: ^1.10.0
dependencies:
  analyzer: ^1.7.1
  build: ^2.0.2
  source_gen: ^1.0.1
  code_builder: ^4.0.0
