name: smartstruct_generator
description: smartstruct - A dart bean mapper annotation processor - the easy nullsafe way!
version: 1.4.0
homepage: https://github.com/smotastic/smartstruct
environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.1
  source_gen_test: ^1.0.2
  test: ^1.22.2
dependencies:
  analyzer: ">=5.0.0 <6.0.0"
  build: ^2.3.1
  code_builder: ^4.4.0
  path: ^1.8.1
  #smartstruct:
  #  path: ../smartstruct
  smartstruct: ^1.4.0
  source_gen: ^1.2.1
#dependency_overrides:
 # smartstruct:
 #   path: ../smartstruct
